### ISSUE TITLE
Can not import torchtt

### ISSUE THREAD

**Issue by junhag2** [ion-g-ion/torchTT#1]
I was trying the torchtt package, but was not able to use it at all.
When run "import torchtt as tntt", it reports a TypeError : 'type' object is not subscriptable
 on torchtt.py  in TT(): cores: list[tn.tensor]

I tried it from downloading the package and run it on windows python 3.8.0, I also tried the directed linked colab notebook on torchTT  repository, neither one is working

Is is a bug or am I missing something?

**Comment by ion-g-ion** [comment]
Hello,

Thank you for your interest in torchTT.
I checked and indeed this error appears on python<=3.9.
I did a new commit #[da5476b](https://github.com/ion-g-ion/torchTT/commit/da5476b1d833b7701fcb7f91b60065d908f7fb66) to resolve this issue and now everything is back to normal.
Just run `pip uninstall torchTT` followeb by `pip install git+https://github.com/ion-g-ion/torchTT` to get the new version.

Best regards,
Ion

**Comment by junhag2** [comment]
Hi Ion,

Thank you for the fast response.
The torchTT now works. But another problem appears, not sure if I should
put it here. Since I was trying to use tt-cme. It seems that in
TTCME-pdfTT, similar problem for function BetaPdfTT.

Perhaps this is due to the same problem. To use this package, should I make
an environment for python3.9?
Thanks
Junhao

**Comment by ion-g-ion** [comment]
Thank you for point it out.
It was the same issue with the python version.
I resolved it in the TT-CME as well.

Best,
Ion
