### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by meandmytram** [ion-g-ion/torchTT#17]
Hey @ion-g-ion, I have spotted a typo! 
https://github.com/ion-g-ion/torchTT/blob/b529efc7e792eefbb468a119ef704783e70250e8/examples/cross_interpolation.py#L7
Here it says "cress" instead of cross.

**Comment by meandmytram** [comment]
https://github.com/ion-g-ion/torchTT/blob/main/examples/cross_interpolation.ipynb

Same here;)

**Comment by ion-g-ion** [comment]
Done
