### ISSUE TITLE
Add a cutoff bound dimension for interpolation functions

### ISSUE THREAD

**Issue by Siddmo6** [ion-g-ion/torchTT#26]
Sometimes when interpolating functions the bound dimension grows without control and eats up all the RAM. It would be good if we could set up a max bound dimension for tensor cross interpolation and also AMEN/dmrg procedures.

**Comment by ion-g-ion** [comment]
Will add the `rmax` parametet to cross interpolation. `amen_solve()` and `dmrg_hadamard()` already have it.
