### ISSUE TITLE
Latest version does not install

### ISSUE THREAD

**Issue by NKlug** [ion-g-ion/torchTT#28]
The latest commit on the main branch cannot be installed via pip (the builds also fail).
`pip install git+https://github.com/ion-g-ion/torchTT` finishes without errors but the package is still not installed.

**To Reproduce**
1. Run `pip install git+https://github.com/ion-g-ion/torchTT`
2. Try to import the package

**Comment by ion-g-ion** [comment]
Hi. The latest version indeed has some issues. I reverted two commits since the new changes were mostly preparation for uploading the project to pypi. What OS are you using?

**Comment by NKlug** [comment]
I'm on Kubuntu 22.04.

**Comment by ion-g-ion** [comment]
pyproject.toml is now fixed
