### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by bhalazs** [ion-g-ion/torchTT#6]
Hey, I really like this project due to many functionalities that are not really available in other packages. However, the one thing that is currently missing (which most other packages have) is broadcasting, e.g. being able to multiply a (k, n, n, n) size tensor with an (n, n, n) tensor without having to use some kind of looping. This makes the handling of batch dimensions very difficult. Is there a particular reason that it is not yet implemented, or are you planning to add it to the library sometime in the future?

**Comment by ion-g-ion** [comment]
Hi. Thanks for the remark. This is an important feature and should be added in the near future.

**Comment by ion-g-ion** [comment]
Added support for PyTorch-like broadcasting for elementwise *,+,- between TT-tensors.

**Comment by bhalazs** [comment]
Excellent, thanks a bunch!
